// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eFood.Services.Database;

#nullable disable

namespace eFood.Services.Migrations
{
    [DbContext(typeof(EFoodContext))]
    [Migration("20251217200707_druga")]
    partial class druga
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eFood.Services.Database.Dojmovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("JeloId")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Dojmovi__3214EC078DD4709C");

                    b.HasIndex("JeloId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Dojmovi", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 8000,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 5,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 8001,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 8002,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 8003,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 5,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 8004,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 3,
                            Opis = "dostava ok"
                        },
                        new
                        {
                            Id = 8005,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 3,
                            Opis = "dostava ok"
                        },
                        new
                        {
                            Id = 8006,
                            JeloId = 5000,
                            KorisnikId = 1002,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9007,
                            JeloId = 5000,
                            KorisnikId = 1001,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9008,
                            JeloId = 5000,
                            KorisnikId = 1001,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9009,
                            JeloId = 5000,
                            KorisnikId = 1001,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9019,
                            JeloId = 5000,
                            KorisnikId = 1001,
                            Ocjena = 3,
                            Opis = "dostava"
                        },
                        new
                        {
                            Id = 9100,
                            JeloId = 5000,
                            KorisnikId = 1001,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9101,
                            JeloId = 5000,
                            KorisnikId = 1007,
                            Ocjena = 5,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9102,
                            JeloId = 5000,
                            KorisnikId = 1007,
                            Ocjena = 5,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9103,
                            JeloId = 5000,
                            KorisnikId = 1007,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9140,
                            JeloId = 5001,
                            KorisnikId = 1007,
                            Ocjena = 5,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9150,
                            JeloId = 5001,
                            KorisnikId = 1007,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9156,
                            JeloId = 5001,
                            KorisnikId = 1002,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9106,
                            JeloId = 5001,
                            KorisnikId = 1001,
                            Ocjena = 5,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9107,
                            JeloId = 5002,
                            KorisnikId = 1001,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9108,
                            JeloId = 5004,
                            KorisnikId = 1002,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9109,
                            JeloId = 5002,
                            KorisnikId = 1001,
                            Ocjena = 4,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9110,
                            JeloId = 5002,
                            KorisnikId = 1002,
                            Ocjena = 3,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9111,
                            JeloId = 5004,
                            KorisnikId = 1001,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9112,
                            JeloId = 5005,
                            KorisnikId = 1001,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9113,
                            JeloId = 5005,
                            KorisnikId = 1001,
                            Ocjena = 3,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9114,
                            JeloId = 5005,
                            KorisnikId = 1002,
                            Ocjena = 4,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9115,
                            JeloId = 5005,
                            KorisnikId = 1002,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        },
                        new
                        {
                            Id = 9116,
                            JeloId = 5005,
                            KorisnikId = 1007,
                            Ocjena = 2,
                            Opis = "odlicna dostava"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naziv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Drzava__3214EC076CFB6820");

                    b.ToTable("Drzava", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            Naziv = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2001,
                            Naziv = "Italija"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DrzavaId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Grad__3214EC07EA4B5287");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Grad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3000,
                            DrzavaId = 2000,
                            Naziv = "Sarajevo"
                        },
                        new
                        {
                            Id = 3010,
                            DrzavaId = 2000,
                            Naziv = "Mostar"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Jelo", b =>
                {
                    b.Property<int>("JeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JeloId"), 1L, 1);

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("money");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JeloId")
                        .HasName("PK__Jelo__3214EC0766C6F668");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Jelo", (string)null);

                    b.HasData(
                        new
                        {
                            JeloId = 5000,
                            Cijena = 15m,
                            KategorijaId = 4000,
                            Naziv = "Margarita",
                            Opis = "top",
                            StateMachine = "active"
                        },
                        new
                        {
                            JeloId = 5001,
                            Cijena = 15m,
                            KategorijaId = 4000,
                            Naziv = "Funghi",
                            Opis = "top",
                            StateMachine = "active"
                        },
                        new
                        {
                            JeloId = 5002,
                            Cijena = 15m,
                            KategorijaId = 4003,
                            Naziv = "Cheesecake",
                            Opis = "top",
                            StateMachine = "active"
                        },
                        new
                        {
                            JeloId = 5004,
                            Cijena = 15m,
                            KategorijaId = 4001,
                            Naziv = "Cevapi",
                            Opis = "top",
                            StateMachine = "cancelled"
                        },
                        new
                        {
                            JeloId = 5005,
                            Cijena = 15m,
                            KategorijaId = 4002,
                            Naziv = "Makaroni",
                            Opis = "top",
                            StateMachine = "active"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"), 1L, 1);

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KategorijaId")
                        .HasName("PK__Kategori__3214EC070A4F4900");

                    b.ToTable("Kategorija", (string)null);

                    b.HasData(
                        new
                        {
                            KategorijaId = 4000,
                            Naziv = "Pizza",
                            Opis = "top"
                        },
                        new
                        {
                            KategorijaId = 4001,
                            Naziv = "Rostilj",
                            Opis = "top"
                        },
                        new
                        {
                            KategorijaId = 4002,
                            Naziv = "Pasta",
                            Opis = "top"
                        },
                        new
                        {
                            KategorijaId = 4003,
                            Naziv = "Desert",
                            Opis = "top"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LozinkaHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LozinkaSalt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Korisnic__3214EC07033A56BF");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnici", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Email = "ajlarahic@gmail.com",
                            Ime = "Ajla",
                            KorisnickoIme = "admin",
                            LozinkaHash = "6CkDF/EMSFa8sAJDqKSRZ1lEiS4=",
                            LozinkaSalt = "dqM5G7yR5b2rmX3pO8OgwQ==",
                            Prezime = "Rahic",
                            Telefon = "066455778"
                        },
                        new
                        {
                            Id = 1002,
                            Email = "lejlaboskailo@gmail.com",
                            Ime = "Lejla",
                            KorisnickoIme = "mobile",
                            LozinkaHash = "hPApkP6EzuQ2I8khWSd6elwOaTQ=",
                            LozinkaSalt = "pmPAq6AxdTXKK/aKmjawyQ==",
                            Prezime = "Boskailo",
                            Telefon = "066455778"
                        },
                        new
                        {
                            Id = 1007,
                            Email = "medisa@gmail.com",
                            Ime = "Medisa",
                            KorisnickoIme = "korisnik",
                            LozinkaHash = "bpTEXMau5N87xfCYHPYr7OTSwwo=",
                            LozinkaSalt = "vN/ZVgjvfGBZn8n+5WYTpg==",
                            Prezime = "Šatara",
                            Telefon = "066455778"
                        },
                        new
                        {
                            Id = 1111,
                            Email = "šejma@gmail.com",
                            Ime = "Šejma",
                            KorisnickoIme = "dostavljac",
                            LozinkaHash = "em5L1tPRQRmza3d6uVE1Td4tNUo=",
                            LozinkaSalt = "TBcJlE90FV8FTC5IXaQHwA==",
                            Prezime = "Tinjak",
                            Telefon = "066455778"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.KorisniciUloge", b =>
                {
                    b.Property<int?>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("KorisnikUlogaId"), 1L, 1);

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogaId")
                        .HasName("PK__KorisniciUloge__1608726E");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge", (string)null);

                    b.HasData(
                        new
                        {
                            KorisnikUlogaId = 1,
                            DatumIzmjene = new DateTime(2025, 12, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 1001,
                            UlogaId = 1
                        },
                        new
                        {
                            KorisnikUlogaId = 5,
                            DatumIzmjene = new DateTime(2025, 12, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 1111,
                            UlogaId = 3
                        },
                        new
                        {
                            KorisnikUlogaId = 2,
                            DatumIzmjene = new DateTime(2025, 12, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 1002,
                            UlogaId = 2
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Korpa", b =>
                {
                    b.Property<int>("KorpaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorpaId"), 1L, 1);

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("JeloId")
                        .HasColumnType("int");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("PrilogId")
                        .HasColumnType("int");

                    b.Property<int?>("PriloziPrilogId")
                        .HasColumnType("int");

                    b.HasKey("KorpaId");

                    b.HasIndex("JeloId");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("PriloziPrilogId");

                    b.ToTable("Korpa", (string)null);

                    b.HasData(
                        new
                        {
                            KorpaId = 7898,
                            Cijena = 30.00m,
                            JeloId = 5000,
                            KategorijaId = 4000,
                            Kolicina = 2,
                            KorisnikId = 1002,
                            PrilogId = 4898
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Lokacija", b =>
                {
                    b.Property<int>("LokacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacijaId"), 1L, 1);

                    b.Property<int?>("KorisniciId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("LokacijaId")
                        .HasName("PK__Lokacija__3214EC07");

                    b.HasIndex("KorisniciId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Lokacija", (string)null);

                    b.HasData(
                        new
                        {
                            LokacijaId = 6000,
                            KorisnikId = 1001,
                            Latitude = 43.856299999999997,
                            Longitude = 18.4131,
                            Vrijeme = new DateTime(2025, 12, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LokacijaId = 6001,
                            KorisnikId = 1002,
                            Latitude = 44.817599999999999,
                            Longitude = 20.456900000000001,
                            Vrijeme = new DateTime(2025, 12, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LokacijaId = 6002,
                            KorisnikId = 1001,
                            Latitude = 43.348599999999998,
                            Longitude = 17.8123,
                            Vrijeme = new DateTime(2025, 12, 17, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DatumNarudzbe")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusNarudzbeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Narudzba__3214EC07423966FD");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("StatusNarudzbeId");

                    b.ToTable("Narudzba", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 6000,
                            DatumNarudzbe = new DateTime(2025, 12, 14, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 1001,
                            StateMachine = "poslano",
                            StatusNarudzbeId = 8010
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Prilozi", b =>
                {
                    b.Property<int>("PrilogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrilogId"), 1L, 1);

                    b.Property<string>("NazivPriloga")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PrilogId")
                        .HasName("PK__Prilozi__3214EC07EA4B5287");

                    b.ToTable("Prilozi", (string)null);

                    b.HasData(
                        new
                        {
                            PrilogId = 4898,
                            NazivPriloga = "Majoneza"
                        },
                        new
                        {
                            PrilogId = 4878,
                            NazivPriloga = "Senf"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Restoran", b =>
                {
                    b.Property<int>("RestoranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestoranId"), 1L, 1);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("NazivRestorana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestoranId");

                    b.HasIndex("GradId");

                    b.ToTable("Restorans");

                    b.HasData(
                        new
                        {
                            RestoranId = 3111,
                            Adresa = "Mostar",
                            Email = "restoran@gmail.com",
                            GradId = 3010,
                            NazivRestorana = "eHrana",
                            Telefon = "066111111"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Status__3214EC071A49A4A8");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Kreirana"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Prihvaćena"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "U toku"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Završena"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Otkazana"
                        },
                        new
                        {
                            Id = 8010,
                            Naziv = "poslano"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.StavkeNarudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Cijena")
                        .HasColumnType("int");

                    b.Property<int?>("JeloId")
                        .HasColumnType("int");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StavkeNa__3214EC0781E952BB");

                    b.HasIndex("JeloId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("StavkeNarudzbe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 7000,
                            Cijena = 30,
                            JeloId = 5000,
                            Kolicina = 2,
                            NarudzbaId = 6000
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Uloge__3214EC076C332449");

                    b.ToTable("Uloge", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Admin",
                            Opis = "Upravljanje sistemom"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Korisnik",
                            Opis = "Pregled podataka"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Dostavljac",
                            Opis = "Dostava narudzbe"
                        });
                });

            modelBuilder.Entity("eFood.Services.Database.Uplata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BrojTransakcije")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("DatumTransakcije")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Iznos")
                        .HasColumnType("money");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("NacinPlacanja")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Uplata__3214EC07C865A4BE");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Uplata");
                });

            modelBuilder.Entity("eFood.Services.Database.Dojmovi", b =>
                {
                    b.HasOne("eFood.Services.Database.Jelo", "Jelo")
                        .WithMany("Dojmovis")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Dojmovi__JeloId__36B12243");

                    b.HasOne("eFood.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Dojmovis")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Dojmovi__Korisni__37A5467C");

                    b.Navigation("Jelo");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eFood.Services.Database.Grad", b =>
                {
                    b.HasOne("eFood.Services.Database.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaId");

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("eFood.Services.Database.Jelo", b =>
                {
                    b.HasOne("eFood.Services.Database.Kategorija", "Kategorija")
                        .WithMany("Jelos")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK__Jelo__Kategorija__2E1BDC42");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("eFood.Services.Database.Korisnici", b =>
                {
                    b.HasOne("eFood.Services.Database.Drzava", null)
                        .WithMany("Korisnicis")
                        .HasForeignKey("DrzavaId");

                    b.HasOne("eFood.Services.Database.Grad", null)
                        .WithMany("Korisnicis")
                        .HasForeignKey("GradId");
                });

            modelBuilder.Entity("eFood.Services.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eFood.Services.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Korisnici__Koris__4316F928");

                    b.HasOne("eFood.Services.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__Korisnici__Uloga__440B1D61");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eFood.Services.Database.Korpa", b =>
                {
                    b.HasOne("eFood.Services.Database.Jelo", "Jelo")
                        .WithMany()
                        .HasForeignKey("JeloId");

                    b.HasOne("eFood.Services.Database.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId");

                    b.HasOne("eFood.Services.Database.Prilozi", "Prilozi")
                        .WithMany()
                        .HasForeignKey("PriloziPrilogId");

                    b.Navigation("Jelo");

                    b.Navigation("Kategorija");

                    b.Navigation("Prilozi");
                });

            modelBuilder.Entity("eFood.Services.Database.Lokacija", b =>
                {
                    b.HasOne("eFood.Services.Database.Korisnici", null)
                        .WithMany("Lokacije")
                        .HasForeignKey("KorisniciId");

                    b.HasOne("eFood.Services.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lokacija_Korisnici");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eFood.Services.Database.Narudzba", b =>
                {
                    b.HasOne("eFood.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Narudzbas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Narudzba__Korisn__32E0915F");

                    b.HasOne("eFood.Services.Database.Status", "StatusNarudzbe")
                        .WithMany("Narudzbas")
                        .HasForeignKey("StatusNarudzbeId")
                        .HasConstraintName("FK__Narudzba__Status__33D4B598");

                    b.Navigation("Korisnik");

                    b.Navigation("StatusNarudzbe");
                });

            modelBuilder.Entity("eFood.Services.Database.Restoran", b =>
                {
                    b.HasOne("eFood.Services.Database.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradId");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("eFood.Services.Database.StavkeNarudzbe", b =>
                {
                    b.HasOne("eFood.Services.Database.Jelo", "Jelo")
                        .WithMany("StavkeNarudzbes")
                        .HasForeignKey("JeloId")
                        .HasConstraintName("FK__StavkeNar__JeloI__3A81B327");

                    b.HasOne("eFood.Services.Database.Narudzba", "Narudzba")
                        .WithMany("StavkeNarudzbes")
                        .HasForeignKey("NarudzbaId")
                        .HasConstraintName("FK__StavkeNar__Narud__3B75D760");

                    b.Navigation("Jelo");

                    b.Navigation("Narudzba");
                });

            modelBuilder.Entity("eFood.Services.Database.Uplata", b =>
                {
                    b.HasOne("eFood.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Uplata")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Uplata__Korisnik__3E52440B");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eFood.Services.Database.Drzava", b =>
                {
                    b.Navigation("Korisnicis");
                });

            modelBuilder.Entity("eFood.Services.Database.Grad", b =>
                {
                    b.Navigation("Korisnicis");
                });

            modelBuilder.Entity("eFood.Services.Database.Jelo", b =>
                {
                    b.Navigation("Dojmovis");

                    b.Navigation("StavkeNarudzbes");
                });

            modelBuilder.Entity("eFood.Services.Database.Kategorija", b =>
                {
                    b.Navigation("Jelos");
                });

            modelBuilder.Entity("eFood.Services.Database.Korisnici", b =>
                {
                    b.Navigation("Dojmovis");

                    b.Navigation("KorisniciUloges");

                    b.Navigation("Lokacije");

                    b.Navigation("Narudzbas");

                    b.Navigation("Uplata");
                });

            modelBuilder.Entity("eFood.Services.Database.Narudzba", b =>
                {
                    b.Navigation("StavkeNarudzbes");
                });

            modelBuilder.Entity("eFood.Services.Database.Status", b =>
                {
                    b.Navigation("Narudzbas");
                });

            modelBuilder.Entity("eFood.Services.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloges");
                });
#pragma warning restore 612, 618
        }
    }
}
